/*
 * This Java source file was generated by the Gradle 'init' task.
 */
import org.testng.annotations.*;
import static org.testng.Assert.*;

public class AppTest {
        
    @Test public void appCountProperly() {
        CountVowels classUnderTest = new CountVowels();
        assertEquals(classUnderTest.CountVowelsF("kjsdhfjaf"), 1, "Counts properly");
    }
}
